In [ ]:
'''
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

'''

In [6]:
def vandermat(x, N=None, increasing=None):
    '''
    Parameters
    ----------
    x : array_like
        1-D input array.
    N : int, optional
        Number of columns in the output.  If `N` is not specified, a square array is returned (``N = len(x)``).
    increasing : bool, optional
        Order of the powers of the columns.  If True, the powers increase
        from left to right, if False (the default) they are reversed.        
    Returns
    -------
    out : ndarray
        Vandermonde matrix.  If `increasing` is False, the first column is``x^(N-1)``, the second ``x^(N-2)`` 
        and so forth. If `increasing` is True, the columns are ``x^0, x^1, ..., x^(N-1)``.
    '''
    x = np.asarray(x)
    if x.ndim != 1:
        raise ValueError('x must be a one-dimensional array or sequence.')
    if N is None:
        N = len(x)
    
    v = np.empty((len(x), N),dtype=np.promote_types(x.dtype, int))
    tmp = v[:, ::-1] if not increasing else v
    if N > 0:
        tmp[:, 0] = 1
    if N > 1:
        tmp[:, 1:] = x[:, None]
        np.multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)
    return v

In [7]:
import numpy as np
x = np.array([1,2,3,5])
N = 3
vandermat(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [8]:
vandermat(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [9]:
vandermat(x,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])